// GENERATED FILE — do not edit by hand.
// Regenerate: node scripts/gen-country-hubs.mjs > api/_countries.js
//
// One source of truth for country hub slugs and names, replacing the two
// hand-typed twenty-country lists that used to live in events-handler.js
// and sitemap-dynamic.js and drift apart. A country appearing in the data
// now gets a hub with no code change at all — which is the whole point,
// because 16 countries with live events had no hub on 5 Aug 2026.
//
// SLUGS ARE PERMANENT. Every slug that has shipped is pinned in the
// generator and it throws if one would change.

export const COUNTRIES = Object.freeze({
  AD: { slug: 'andorra', name: "Andorra" },
  AE: { slug: 'united-arab-emirates', name: "the United Arab Emirates" },
  AF: { slug: 'afghanistan', name: "Afghanistan" },
  AG: { slug: 'antigua-and-barbuda', name: "Antigua & Barbuda" },
  AI: { slug: 'anguilla', name: "Anguilla" },
  AL: { slug: 'albania', name: "Albania" },
  AM: { slug: 'armenia', name: "Armenia" },
  AO: { slug: 'angola', name: "Angola" },
  AQ: { slug: 'antarctica', name: "Antarctica" },
  AR: { slug: 'argentina', name: "Argentina" },
  AS: { slug: 'american-samoa', name: "American Samoa" },
  AT: { slug: 'austria', name: "Austria" },
  AU: { slug: 'australia', name: "Australia" },
  AW: { slug: 'aruba', name: "Aruba" },
  AX: { slug: 'aland-islands', name: "Åland Islands" },
  AZ: { slug: 'azerbaijan', name: "Azerbaijan" },
  BA: { slug: 'bosnia-and-herzegovina', name: "Bosnia & Herzegovina" },
  BB: { slug: 'barbados', name: "Barbados" },
  BD: { slug: 'bangladesh', name: "Bangladesh" },
  BE: { slug: 'belgium', name: "Belgium" },
  BF: { slug: 'burkina-faso', name: "Burkina Faso" },
  BG: { slug: 'bulgaria', name: "Bulgaria" },
  BH: { slug: 'bahrain', name: "Bahrain" },
  BI: { slug: 'burundi', name: "Burundi" },
  BJ: { slug: 'benin', name: "Benin" },
  BL: { slug: 'saint-barthelemy', name: "St. Barthélemy" },
  BM: { slug: 'bermuda', name: "Bermuda" },
  BN: { slug: 'brunei', name: "Brunei" },
  BO: { slug: 'bolivia', name: "Bolivia" },
  BQ: { slug: 'caribbean-netherlands', name: "Caribbean Netherlands" },
  BR: { slug: 'brazil', name: "Brazil" },
  BS: { slug: 'bahamas', name: "the Bahamas" },
  BT: { slug: 'bhutan', name: "Bhutan" },
  BV: { slug: 'bouvet-island', name: "Bouvet Island" },
  BW: { slug: 'botswana', name: "Botswana" },
  BY: { slug: 'belarus', name: "Belarus" },
  BZ: { slug: 'belize', name: "Belize" },
  CA: { slug: 'canada', name: "Canada" },
  CC: { slug: 'cocos-keeling-islands', name: "Cocos (Keeling) Islands" },
  CD: { slug: 'congo-kinshasa', name: "the Democratic Republic of the Congo" },
  CF: { slug: 'central-african-republic', name: "Central African Republic" },
  CG: { slug: 'congo-brazzaville', name: "the Republic of the Congo" },
  CH: { slug: 'switzerland', name: "Switzerland" },
  CI: { slug: 'cote-divoire', name: "Côte d’Ivoire" },
  CK: { slug: 'cook-islands', name: "Cook Islands" },
  CL: { slug: 'chile', name: "Chile" },
  CM: { slug: 'cameroon', name: "Cameroon" },
  CN: { slug: 'china', name: "China" },
  CO: { slug: 'colombia', name: "Colombia" },
  CR: { slug: 'costa-rica', name: "Costa Rica" },
  CU: { slug: 'cuba', name: "Cuba" },
  CV: { slug: 'cape-verde', name: "Cape Verde" },
  CW: { slug: 'curacao', name: "Curaçao" },
  CX: { slug: 'christmas-island', name: "Christmas Island" },
  CY: { slug: 'cyprus', name: "Cyprus" },
  CZ: { slug: 'czechia', name: "the Czech Republic" },
  DE: { slug: 'germany', name: "Germany" },
  DJ: { slug: 'djibouti', name: "Djibouti" },
  DK: { slug: 'denmark', name: "Denmark" },
  DM: { slug: 'dominica', name: "Dominica" },
  DO: { slug: 'dominican-republic', name: "the Dominican Republic" },
  DZ: { slug: 'algeria', name: "Algeria" },
  EC: { slug: 'ecuador', name: "Ecuador" },
  EE: { slug: 'estonia', name: "Estonia" },
  EG: { slug: 'egypt', name: "Egypt" },
  EH: { slug: 'western-sahara', name: "Western Sahara" },
  ER: { slug: 'eritrea', name: "Eritrea" },
  ES: { slug: 'spain', name: "Spain" },
  ET: { slug: 'ethiopia', name: "Ethiopia" },
  FI: { slug: 'finland', name: "Finland" },
  FJ: { slug: 'fiji', name: "Fiji" },
  FK: { slug: 'falkland-islands', name: "Falkland Islands" },
  FM: { slug: 'micronesia', name: "Micronesia" },
  FO: { slug: 'faroe-islands', name: "Faroe Islands" },
  FR: { slug: 'france', name: "France" },
  GA: { slug: 'gabon', name: "Gabon" },
  GB: { slug: 'united-kingdom', name: "the United Kingdom" },
  GD: { slug: 'grenada', name: "Grenada" },
  GE: { slug: 'georgia', name: "Georgia" },
  GF: { slug: 'french-guiana', name: "French Guiana" },
  GG: { slug: 'guernsey', name: "Guernsey" },
  GH: { slug: 'ghana', name: "Ghana" },
  GI: { slug: 'gibraltar', name: "Gibraltar" },
  GL: { slug: 'greenland', name: "Greenland" },
  GM: { slug: 'gambia', name: "the Gambia" },
  GN: { slug: 'guinea', name: "Guinea" },
  GP: { slug: 'guadeloupe', name: "Guadeloupe" },
  GQ: { slug: 'equatorial-guinea', name: "Equatorial Guinea" },
  GR: { slug: 'greece', name: "Greece" },
  GS: { slug: 'south-georgia-and-south-sandwich-islands', name: "South Georgia & South Sandwich Islands" },
  GT: { slug: 'guatemala', name: "Guatemala" },
  GU: { slug: 'guam', name: "Guam" },
  GW: { slug: 'guinea-bissau', name: "Guinea-Bissau" },
  GY: { slug: 'guyana', name: "Guyana" },
  HK: { slug: 'hong-kong', name: "Hong Kong" },
  HM: { slug: 'heard-and-mcdonald-islands', name: "Heard & McDonald Islands" },
  HN: { slug: 'honduras', name: "Honduras" },
  HR: { slug: 'croatia', name: "Croatia" },
  HT: { slug: 'haiti', name: "Haiti" },
  HU: { slug: 'hungary', name: "Hungary" },
  ID: { slug: 'indonesia', name: "Indonesia" },
  IE: { slug: 'ireland', name: "Ireland" },
  IL: { slug: 'israel', name: "Israel" },
  IM: { slug: 'isle-of-man', name: "Isle of Man" },
  IN: { slug: 'india', name: "India" },
  IO: { slug: 'british-indian-ocean-territory', name: "British Indian Ocean Territory" },
  IQ: { slug: 'iraq', name: "Iraq" },
  IR: { slug: 'iran', name: "Iran" },
  IS: { slug: 'iceland', name: "Iceland" },
  IT: { slug: 'italy', name: "Italy" },
  JE: { slug: 'jersey', name: "Jersey" },
  JM: { slug: 'jamaica', name: "Jamaica" },
  JO: { slug: 'jordan', name: "Jordan" },
  JP: { slug: 'japan', name: "Japan" },
  KE: { slug: 'kenya', name: "Kenya" },
  KG: { slug: 'kyrgyzstan', name: "Kyrgyzstan" },
  KH: { slug: 'cambodia', name: "Cambodia" },
  KI: { slug: 'kiribati', name: "Kiribati" },
  KM: { slug: 'comoros', name: "Comoros" },
  KN: { slug: 'saint-kitts-and-nevis', name: "St. Kitts & Nevis" },
  KP: { slug: 'north-korea', name: "North Korea" },
  KR: { slug: 'south-korea', name: "South Korea" },
  KW: { slug: 'kuwait', name: "Kuwait" },
  KY: { slug: 'cayman-islands', name: "Cayman Islands" },
  KZ: { slug: 'kazakhstan', name: "Kazakhstan" },
  LA: { slug: 'laos', name: "Laos" },
  LB: { slug: 'lebanon', name: "Lebanon" },
  LC: { slug: 'saint-lucia', name: "St. Lucia" },
  LI: { slug: 'liechtenstein', name: "Liechtenstein" },
  LK: { slug: 'sri-lanka', name: "Sri Lanka" },
  LR: { slug: 'liberia', name: "Liberia" },
  LS: { slug: 'lesotho', name: "Lesotho" },
  LT: { slug: 'lithuania', name: "Lithuania" },
  LU: { slug: 'luxembourg', name: "Luxembourg" },
  LV: { slug: 'latvia', name: "Latvia" },
  LY: { slug: 'libya', name: "Libya" },
  MA: { slug: 'morocco', name: "Morocco" },
  MC: { slug: 'monaco', name: "Monaco" },
  MD: { slug: 'moldova', name: "Moldova" },
  ME: { slug: 'montenegro', name: "Montenegro" },
  MF: { slug: 'saint-martin', name: "St. Martin" },
  MG: { slug: 'madagascar', name: "Madagascar" },
  MH: { slug: 'marshall-islands', name: "Marshall Islands" },
  MK: { slug: 'north-macedonia', name: "North Macedonia" },
  ML: { slug: 'mali', name: "Mali" },
  MM: { slug: 'myanmar', name: "Myanmar" },
  MN: { slug: 'mongolia', name: "Mongolia" },
  MO: { slug: 'macau', name: "Macau" },
  MP: { slug: 'northern-mariana-islands', name: "Northern Mariana Islands" },
  MQ: { slug: 'martinique', name: "Martinique" },
  MR: { slug: 'mauritania', name: "Mauritania" },
  MS: { slug: 'montserrat', name: "Montserrat" },
  MT: { slug: 'malta', name: "Malta" },
  MU: { slug: 'mauritius', name: "Mauritius" },
  MV: { slug: 'maldives', name: "the Maldives" },
  MW: { slug: 'malawi', name: "Malawi" },
  MX: { slug: 'mexico', name: "Mexico" },
  MY: { slug: 'malaysia', name: "Malaysia" },
  MZ: { slug: 'mozambique', name: "Mozambique" },
  NA: { slug: 'namibia', name: "Namibia" },
  NC: { slug: 'new-caledonia', name: "New Caledonia" },
  NE: { slug: 'niger', name: "Niger" },
  NF: { slug: 'norfolk-island', name: "Norfolk Island" },
  NG: { slug: 'nigeria', name: "Nigeria" },
  NI: { slug: 'nicaragua', name: "Nicaragua" },
  NL: { slug: 'netherlands', name: "the Netherlands" },
  NO: { slug: 'norway', name: "Norway" },
  NP: { slug: 'nepal', name: "Nepal" },
  NR: { slug: 'nauru', name: "Nauru" },
  NU: { slug: 'niue', name: "Niue" },
  NZ: { slug: 'new-zealand', name: "New Zealand" },
  OM: { slug: 'oman', name: "Oman" },
  PA: { slug: 'panama', name: "Panama" },
  PE: { slug: 'peru', name: "Peru" },
  PF: { slug: 'french-polynesia', name: "French Polynesia" },
  PG: { slug: 'papua-new-guinea', name: "Papua New Guinea" },
  PH: { slug: 'philippines', name: "the Philippines" },
  PK: { slug: 'pakistan', name: "Pakistan" },
  PL: { slug: 'poland', name: "Poland" },
  PM: { slug: 'saint-pierre-and-miquelon', name: "St. Pierre & Miquelon" },
  PN: { slug: 'pitcairn-islands', name: "Pitcairn Islands" },
  PR: { slug: 'puerto-rico', name: "Puerto Rico" },
  PS: { slug: 'palestine', name: "Palestinian Territories" },
  PT: { slug: 'portugal', name: "Portugal" },
  PW: { slug: 'palau', name: "Palau" },
  PY: { slug: 'paraguay', name: "Paraguay" },
  QA: { slug: 'qatar', name: "Qatar" },
  RE: { slug: 'reunion', name: "Réunion" },
  RO: { slug: 'romania', name: "Romania" },
  RS: { slug: 'serbia', name: "Serbia" },
  RU: { slug: 'russia', name: "Russia" },
  RW: { slug: 'rwanda', name: "Rwanda" },
  SA: { slug: 'saudi-arabia', name: "Saudi Arabia" },
  SB: { slug: 'solomon-islands', name: "Solomon Islands" },
  SC: { slug: 'seychelles', name: "Seychelles" },
  SD: { slug: 'sudan', name: "Sudan" },
  SE: { slug: 'sweden', name: "Sweden" },
  SG: { slug: 'singapore', name: "Singapore" },
  SH: { slug: 'saint-helena', name: "St. Helena" },
  SI: { slug: 'slovenia', name: "Slovenia" },
  SJ: { slug: 'svalbard-and-jan-mayen', name: "Svalbard & Jan Mayen" },
  SK: { slug: 'slovakia', name: "Slovakia" },
  SL: { slug: 'sierra-leone', name: "Sierra Leone" },
  SM: { slug: 'san-marino', name: "San Marino" },
  SN: { slug: 'senegal', name: "Senegal" },
  SO: { slug: 'somalia', name: "Somalia" },
  SR: { slug: 'suriname', name: "Suriname" },
  SS: { slug: 'south-sudan', name: "South Sudan" },
  ST: { slug: 'sao-tome-and-principe', name: "São Tomé & Príncipe" },
  SV: { slug: 'el-salvador', name: "El Salvador" },
  SX: { slug: 'sint-maarten', name: "Sint Maarten" },
  SY: { slug: 'syria', name: "Syria" },
  SZ: { slug: 'eswatini', name: "Eswatini" },
  TC: { slug: 'turks-and-caicos-islands', name: "Turks & Caicos Islands" },
  TD: { slug: 'chad', name: "Chad" },
  TF: { slug: 'french-southern-territories', name: "French Southern Territories" },
  TG: { slug: 'togo', name: "Togo" },
  TH: { slug: 'thailand', name: "Thailand" },
  TJ: { slug: 'tajikistan', name: "Tajikistan" },
  TK: { slug: 'tokelau', name: "Tokelau" },
  TL: { slug: 'timor-leste', name: "Timor-Leste" },
  TM: { slug: 'turkmenistan', name: "Turkmenistan" },
  TN: { slug: 'tunisia', name: "Tunisia" },
  TO: { slug: 'tonga', name: "Tonga" },
  TR: { slug: 'turkiye', name: "Türkiye" },
  TT: { slug: 'trinidad-and-tobago', name: "Trinidad & Tobago" },
  TV: { slug: 'tuvalu', name: "Tuvalu" },
  TW: { slug: 'taiwan', name: "Taiwan" },
  TZ: { slug: 'tanzania', name: "Tanzania" },
  UA: { slug: 'ukraine', name: "Ukraine" },
  UG: { slug: 'uganda', name: "Uganda" },
  UM: { slug: 'u-s-outlying-islands', name: "U.S. Outlying Islands" },
  US: { slug: 'united-states', name: "the United States" },
  UY: { slug: 'uruguay', name: "Uruguay" },
  UZ: { slug: 'uzbekistan', name: "Uzbekistan" },
  VA: { slug: 'vatican-city', name: "Vatican City" },
  VC: { slug: 'saint-vincent-and-grenadines', name: "St. Vincent & Grenadines" },
  VE: { slug: 'venezuela', name: "Venezuela" },
  VG: { slug: 'british-virgin-islands', name: "British Virgin Islands" },
  VI: { slug: 'us-virgin-islands', name: "the US Virgin Islands" },
  VN: { slug: 'vietnam', name: "Vietnam" },
  VU: { slug: 'vanuatu', name: "Vanuatu" },
  WF: { slug: 'wallis-and-futuna', name: "Wallis & Futuna" },
  WS: { slug: 'samoa', name: "Samoa" },
  YE: { slug: 'yemen', name: "Yemen" },
  YT: { slug: 'mayotte', name: "Mayotte" },
  ZA: { slug: 'south-africa', name: "South Africa" },
  ZM: { slug: 'zambia', name: "Zambia" },
  ZW: { slug: 'zimbabwe', name: "Zimbabwe" },
});

const BY_SLUG = Object.freeze(Object.fromEntries(
  Object.entries(COUNTRIES).map(([code, c]) => [c.slug, { code, ...c }])
));

// Resolve a URL slug to a country, or null if it is not one. Callers use
// null to fall through to the next namespace (a bookable route), exactly
// as the hand-written map did.
export function countryBySlug(slug) {
  return BY_SLUG[String(slug || '').toLowerCase()] || null;
}

export function countryByCode(code) {
  const c = COUNTRIES[String(code || '').toUpperCase()];
  return c ? { code: String(code).toUpperCase(), ...c } : null;
}
