/**
 * SwimAnalysis: the normalised model behind every Aqua Sharks SwimBETTER report.
 *
 * Layers (never mixed):
 *   SOURCE        what EO printed          -> session, metrics, forceDistribution, lapComparisons, eoObservations ...
 *   FINDINGS      what Aqua Sharks derived -> aquaSharksFindings, priorities (generated by the rule engine)
 *   COACH REVIEW  what a coach decided     -> coachReview, coachNotes
 * The engine reads SOURCE and writes FINDINGS. It never edits SOURCE.
 */

export type DataStatus = 'COMPLETE' | 'PARTIAL' | 'AMBIGUOUS' | 'MISSING';
export type Classification = 'MEASURED' | 'OBSERVED' | 'INFERRED' | 'COACH_CONFIRMATION_REQUIRED';
export type Confidence = 'HIGH' | 'MODERATE' | 'LOW';
export type ProfileId = 'JUNIOR' | 'PERFORMANCE' | 'MASTERS_OPEN_WATER' | 'COACH';
export type SwimmerProfileId = Exclude<ProfileId, 'COACH'>;

/**
 * Where a value came from.
 *  EO_REPORT       printed in the report text or a table
 *  EO_IMAGE_LABEL  printed text read out of an embedded image (vision/OCR)
 *  CHART_READ      estimated from a plot with no data labels: never auto-filled, coach-entered only
 *  COACH_SUPPLIED  entered or confirmed by a coach
 *  DERIVED         computed by Aqua Sharks from other values
 */
export type Origin = 'EO_REPORT' | 'EO_IMAGE_LABEL' | 'CHART_READ' | 'COACH_SUPPLIED' | 'DERIVED' | 'FIXTURE';

/** How a field was extracted and how sure the extractor is. Present on parser output. */
export interface ExtractionInfo {
  method: 'TEXT' | 'TABLE' | 'STRUCT' | 'IMAGE' | 'CHART' | 'MODEL' | 'RULE' | 'MANUAL';
  confidence: 'HIGH' | 'MODERATE' | 'LOW';
  /** Where in the document: section heading, paragraph index, table cell, image index, page. */
  locator?: { section?: string; paragraph?: number; tableCell?: string; image?: number; page?: number };
}

/** Why a value is MISSING. Lets the debug view tell "this layout never has it" from "we failed to read it" from "that step has not run yet". */
export type Absence = 'NOT_IN_SOURCE' | 'EXTRACTION_FAILED' | 'COACH_REQUIRED' | 'NOT_ATTEMPTED';

export interface Provenance {
  origin: Origin;
  /** Where in the source: "summary line", "distribution table", "force-field image" etc. */
  location?: string;
  /** A short label as printed (a field name or a number), never a sentence of source prose. */
  raw?: string;
  note?: string;
  /** Present when a parser produced the value. */
  extraction?: ExtractionInfo;
}

/** A numeric value. `value` is null when absent or when only a range is known. Never filled by inference. */
export interface Measured {
  value: number | null;
  unit?: string;
  status: DataStatus;
  /** Set when status is MISSING. */
  absence?: Absence;
  /** Source said "approximately" or similar. Caps confidence at MODERATE. */
  approximate?: boolean;
  /** Source gave a range instead of a point value. Never collapsed to a midpoint. */
  range?: [number, number];
  provenance: Provenance;
  /**
   * Other values for the SAME quantity printed elsewhere in the source. Never discarded.
   * `value` is the one the engine uses; that is a source-selection decision (see selectionBasis), not ground truth.
   * Alternates that differ by more than rounding cap confidence at MODERATE.
   */
  alternates?: { value: number; location: string }[];
  /** Why `value` was selected over the alternates. Expected whenever alternates exist. */
  selectionBasis?: string;
}

/** A qualitative observation from a closed vocabulary. */
export interface Observed<T extends string = string> {
  value: T | null;
  status: DataStatus;
  absence?: Absence;
  provenance: Provenance;
}

export interface ForceShares {
  propulsivePct: Measured;
  downwardPct: Measured;
  upwardPct: Measured;
  leftwardPct: Measured;
  rightwardPct: Measured;
  handDragPct: Measured;
}

/** Which lap(s) a comparison endpoint refers to. Identifiers are kept as the source/coach gave them. */
export interface LapRef {
  /** Actual lap numbers, 1-based. Never inferred from the words "early" or "late". */
  laps: number[];
  /** Distance covered by those laps, e.g. { from: 0, to: 25 } for lap 1 of a 25 m pool. Null when unknown. */
  distanceM: { from: number; to: number } | null;
  status: DataStatus;
  provenance: Provenance;
}

/**
 * ENDPOINT_CHANGE: two laps compared (e.g. lap 1 vs lap 8). Says nothing about what happened in between.
 * MULTI_LAP_TREND: a measured series across several laps. Only this may be described as a trend.
 */
export type ComparisonKind = 'ENDPOINT_CHANGE' | 'MULTI_LAP_TREND';

export interface FromTo {
  from: Measured;
  to: Measured;
  /** Change as reported by the source: percent, or percentage points when `changeUnit` is 'points'. */
  change: Measured;
  changeUnit: 'pct' | 'points';
}

export interface LapComparison {
  id: string;
  kind: ComparisonKind;
  from: LapRef;
  to: LapRef;
  strokeRate: FromTo;
  pullPower: FromTo;
  propulsivePower: FromTo;
  forceShares: { from: ForceShares; to: ForceShares };
}

export type PowerShape = 'SINGLE_PEAK' | 'MULTI_PEAK' | 'SHOULDER';
export type RelativeOutput = 'HIGHER' | 'LOWER' | 'SIMILAR';

export interface PhaseSet { glidePct: Measured; pullPct: Measured; recoveryPct: Measured }
/**
 * Stroke phases. Lap averages and individual strokes are SEPARATE collections by construction:
 * swimmer-facing conclusions read `lapAverages` only, and an individual stroke can never stand in for a lap average.
 */
export interface ArmPhases {
  lapAverages: { lap: number; phases: PhaseSet }[];
  individualStrokes: { lap: number; stroke: number; phases: PhaseSet }[];
}

export interface PowerSide {
  shape: Observed<PowerShape>;
  /** EO-detected share of strokes with a double peak, per lap (percent). Index 0 = lap 1. Empty when not printed. */
  doublePeakPctByLap: Measured[];
}

/**
 * What kind of statement EO made. Aqua Sharks keeps all of them, but only MEASUREMENT_STATEMENTs are treated as evidence.
 * DIAGNOSTIC_INTERPRETATION (e.g. a biomechanical cause) is EO's inference: preserved, never shown to a swimmer unreviewed.
 */
export type ClaimType = 'MEASUREMENT_STATEMENT' | 'DIAGNOSTIC_INTERPRETATION' | 'RECOMMENDATION';
export type EoArea =
  | 'OVERVIEW' | 'STROKE_RATE_POWER' | 'FORCE_FIELD' | 'HAND_PATH' | 'CONSISTENCY'
  | 'STROKE_PHASES' | 'POWER_VS_TIME' | 'HAND_PATH_AND_POWER';

/** A SHORT PARAPHRASE of an EO statement. Verbatim EO prose is never stored in source control. */
export interface EoObservation {
  id: string; area: EoArea; text: string; claimType: ClaimType;
  /** How claimType was decided. Classification is not deterministic, so the basis is always recorded. */
  claimTypeBasis: 'RULE' | 'MODEL' | 'COACH';
  claimTypeConfidence: 'HIGH' | 'MODERATE' | 'LOW';
  provenance: Provenance;
}
export interface EoRecommendation {
  id: string; area: EoArea | 'GENERAL'; text: string; provenance: Provenance;
  /** COACH_ONLY for clinical or sensitive advice (e.g. a referral). Never auto-surfaced to swimmers or parents. */
  audience: 'SWIMMER' | 'COACH_ONLY';
  truncated?: boolean;
}

/** A problem in the source itself. Contradictory claims are preserved as flags, never silently reconciled. */
export interface SourceIssue {
  id: string; severity: 'INFO' | 'WARN';
  kind: 'CONTRADICTION' | 'CONFLICTING_VALUES' | 'UNRECONCILED_FIGURE' | 'TRUNCATION' | 'UNIT_AMBIGUITY' | 'UNLABELLED_LAP';
  fields: string[]; message: string;
}
export interface ReferenceRange { text: string; lo: number | null; hi: number | null; provenance: Provenance }

export interface SourceDocument {
  kind: 'EO_REPORT_DOCX' | 'EO_REPORT_PDF' | 'EO_APP_SCREENSHOT' | 'COACH_ENTRY' | 'FIXTURE';
  filename: string | null;
  sha256: string | null;
  /** Which EO views this document supplies. */
  views: EoArea[];
}

/** A printed item that has no home in the schema. Preserved, never interpreted. */
export interface UnmappedItem { label: string; value: string; location: string }

/** A force-field reading taken from an image. The lap it shows is often unlabelled, so it is held here until a coach assigns it. */
export interface ForceFieldReading {
  id: string;
  image: number | null;
  lap: LapRef;
  shares: ForceShares;
  impulse: { left: Measured; right: Measured };
  provenance: Provenance;
}

export interface SwimAnalysis {
  schemaVersion: 3;
  swimmer: { name: string; age: Measured; communicationProfile: ProfileId };
  session: {
    date: Observed<string>;
    /** Time of day as printed. No time-zone conversion is applied. */
    startTime: Observed<string>;
    stroke: Observed<string>;
    distanceM: Measured;
    timeS: Measured;
    laps: Measured;
    strokeCount: Measured;
    poolLengthM: Measured;
    location: Observed<string>;
  };
  source: {
    provider: 'EO Labs'; product: 'SwimBETTER';
    /** Every input behind this analysis: a report, screenshots, coach entry. */
    documents: SourceDocument[];
    /** Detected report layout, e.g. EO_AI_DOCX_V1. Null when not parsed. */
    layout: string | null;
    /** EO's own analysis context, e.g. "Distance". Context only, not an Aqua Sharks classification. */
    analysisContext: { swimmerType: string | null };
    extractedAt: string | null;
    parserVersion: string | null;
    notes: string[];
  };
  metrics: {
    strokeRate: Measured;            // strokes per minute, whole swim
    distancePerStrokeM: Measured;
    avgForceN: Measured;             // EO "FPS"
    avgPowerW: Measured;             // EO "PPS"
    workKj: Measured;
    propulsivePct: Measured;         // summary-line value; the force-distribution table carries its own (see selectionBasis)
  };
  /** Whole-swim shares. Per-lap shares live inside lapComparisons. */
  forceDistribution: { overall: ForceShares };
  leftRight: {
    /** EO labels this per-arm figure "Avg Impulse" and gives watts. Whether it is per-arm power is unconfirmed, so it keeps EO's label. */
    avgImpulseW: { left: Measured; right: Measured };
    impulse: { left: Measured; right: Measured };
    relativeOutput: { left: Observed<RelativeOutput>; right: Observed<RelativeOutput> };
    /** Did the gap persist across laps? As stated by EO or the coach. */
    persistence: Observed<'ALL_LAPS' | 'SOME_LAPS' | 'ONE_LAP'>;
    /**
     * Which arm produced more power in each lap. `higher` is what EO's text says (rule-read) or, when the coach has entered
     * both per-lap figures, what those figures show. Absent on analyses saved before this field existed: treat as [].
     */
    byLap?: { lap: number; higher: Observed<'LEFT' | 'RIGHT' | 'EQUAL'>; leftW: Measured; rightW: Measured }[];
  };
  /** Explicit lap comparisons. Empty when the source gives none. */
  lapComparisons: LapComparison[];
  /** Force-field image readings awaiting a lap assignment. */
  forceFieldReadings: ForceFieldReading[];
  handPath: { left: Observed<string>; right: Observed<string> };   // geometry descriptions only; no fault inference
  consistency: { left: Observed<string>; right: Observed<string>; withinLap: Observed<string>; betweenLaps: Observed<string> };
  strokePhases: { left: ArmPhases; right: ArmPhases };
  powerProfile: { left: PowerSide; right: PowerSide };
  /** The hand-path / force bridge. COMPLETE only when the source shows where in the stroke force events occur. */
  handPathAndPower: { status: DataStatus; note?: string };
  eoObservations: EoObservation[];
  eoRecommendations: EoRecommendation[];
  /** EO's own reference ranges, as printed. Source evidence only: Aqua Sharks does not adopt them as thresholds. */
  eoReferenceRanges: Record<string, ReferenceRange>;
  /** The swimmer type and stroke EO's reference ranges are specific to. */
  eoReferenceContext: { swimmerType: string | null; stroke: string | null };
  /** Printed items with no schema field (e.g. an unexplained flag). Preserved, never interpreted. */
  unmapped: UnmappedItem[];
  /** Contradictions, truncation and unreconciled figures found in the source itself. */
  sourceIssues: SourceIssue[];

  // ---- derived and reviewed layers ----
  aquaSharksFindings: Finding[];
  priorities: Priority[];
  coachNotes: { id: string; text: string; findingId?: string }[];
  coachReview: {
    findings: Record<string, FindingReview>;
    /** Coach-chosen order of finding ids for priorities. Overrides engine rank. */
    priorityOrder?: string[];
    /** Drill chosen by the coach per finding id. */
    drillChoice?: Record<string, string>;
    /**
     * EO's diagnostic sentences are hidden from swimmers until the coach decides. APPROVED shows EO's sentence,
     * EDITED shows `editedText`, anything else (or absent) stays hidden. Keyed by EoObservation id.
     */
    eoClaims?: Record<string, { status: 'APPROVED' | 'EDITED' | 'HIDDEN'; editedText?: string }>;
    /** A short personal note from the coach, shown near the top of the swimmer report. */
    coachNote?: string;
  };
  baseline: {
    capturedOn: string | null; metrics: Record<string, number>;
    /** Set when the baseline is an earlier session of the same swimmer (see progress.js). Drives the "since last time" section. */
    context?: { stroke: string | null; distanceM: number | null };
  };
}

export interface FindingReview {
  status: 'PENDING' | 'APPROVED' | 'EDITED' | 'SUPPRESSED';
  /** Replacement swimmer-facing text. */
  editedText?: string;
  /** Coach confirms a technical interpretation. Needed before an INFERRED finding reaches a swimmer. */
  technicalConfirmed?: boolean;
  note?: string;
}

export interface Finding {
  id: string;
  ruleId: string;
  kind: 'OPPORTUNITY' | 'STRENGTH' | 'CONTEXT';
  title: string;
  /** Classification of the main claim. Inferred diagnoses can never carry MEASURED. */
  classification: Classification;
  confidence: Confidence;
  /** Dot-paths into SwimAnalysis that this finding rests on. */
  evidence: string[];
  measurement: string[];
  observation: string | null;
  interpretation: { text: string; classification: Classification } | null;
  recommendation: string | null;
  text: { JUNIOR: string; PERFORMANCE: string; MASTERS_OPEN_WATER: string; COACH: string };
  caveats: string[];
  relationships: string[];
  coachConfirmation: { required: boolean; reason?: string; evidenceNeeded?: string[] };
  /**
   * Independent measures that point the same way. This is corroboration, NOT an equation: no formula links the
   * signals, and none is assumed unless the source documents one.
   */
  corroboration?: {
    status: 'CORROBORATED' | 'PARTIAL' | 'CONFLICTING' | 'NOT_TESTABLE';
    signals: { id: string; label: string; direction: 'DOWN' | 'UP' | 'UNCLEAR' }[];
    detail: string;
  };
  impact: number;
  score: number;
  review: FindingReview;
  /** Structured data the report view needs (rows, categories, arms). Derived only; never source. */
  meta: Record<string, any>;
}

export interface Priority {
  id: string;
  findingIds: string[];
  rank: number;
  title: string;
  why: Record<SwimmerProfileId, string>;
  feel: string;
  cue: string;
  drillId: string | null;
  /** False when the evidence is not yet fit for a swimmer (inferred / awaiting confirmation). */
  swimmerFacing: boolean;
  coachOnlyReason?: string;
  ruleId: string;
  classification: Classification;
  confidence: Confidence;
  suppressed?: boolean;
  drill: Drill | null;
  /** True when this priority appears in the profile's swimmer-facing report (after the profile's priority cap). */
  included: boolean;
}

export interface Drill {
  id: string; name: string; tags: string[]; what: string; feel: string; why: string; origin: string;
  /** All library drills are DRAFT until a coach approves them. */
  status: 'DRAFT' | 'APPROVED';
}

// ---- report model (what the view renders) ----
export interface ProfileConfig {
  id: ProfileId;
  label: string;
  maxPriorities: number;
  maxHeroMetrics: number;
  heroMetricOrder: string[];
  showNumbers: 'MINIMAL' | 'STANDARD' | 'FULL';
  showEvidence: boolean;
  showConfidence: boolean;
}

export interface ReportSection {
  id: 'HERO' | 'NOTE' | 'STRENGTHS' | 'PROGRESS' | 'POWER' | 'COMPARISON' | 'ARMS' | 'FOCUS' | 'NEXT' | 'EVIDENCE' | 'DATA_QUALITY' | 'SOURCE';
  status: DataStatus;
  data: unknown;
}

export interface ReportModel {
  profile: ProfileConfig;
  sections: ReportSection[];
}
