// Read-only dry run: replays the CURRENT location parser over the stored
// raw_source_values of every candidate that has no country_code, and
// reports what it would resolve now.
//
// Unchanged pages are never re-extracted (the page-hash cache skips them),
// so a parser fix does not retroactively repair stored rows. This script
// exists to answer the only question that matters before backfilling them
// by hand: does the fixed parser, given the bytes we already captured,
// produce the right country? It writes nothing.
//
//   npx tsx scripts/replay-country-resolution.ts
//   npx tsx scripts/replay-country-resolution.ts --venues   (group by venue)

import { createClient } from '@supabase/supabase-js';
import { mergeLocations, parseJsonLdPlace, parseLocationText } from '../src/normalize/location.js';

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_KEY;
if (!url || !key) throw new Error('SUPABASE_URL and SUPABASE_SERVICE_KEY are required');

const db = createClient(url, key, { auth: { persistSession: false } });

function offsetOf(iso: string | null): string | null {
  if (!iso) return null;
  const m = /([+-]\d{2}:\d{2}|Z)$/.exec(iso.trim());
  if (m) return m[1] ?? null;
  const compact = /T.*([+-])(\d{2})(\d{2})$/.exec(iso.trim());
  return compact ? `${compact[1]}${compact[2]}:${compact[3]}` : null;
}

const { data, error } = await db
  .from('discovery_candidate_events')
  .select('id, canonical_name, city, region, location_text, country_code, raw_source_values, promoted_edition_id')
  .is('country_code', null);
if (error) throw new Error(error.message);

const rows = data ?? [];
let resolved = 0;
const byCountry = new Map<string, number>();
const stillNull: string[] = [];
const sqlPairs: Array<[string, string]> = [];

for (const r of rows) {
  const raw = (r.raw_source_values ?? {}) as Record<string, unknown>;
  const utcOffset = offsetOf((raw.jsonLdStartDate as string) ?? null);
  const merged = mergeLocations(
    parseJsonLdPlace(raw.jsonLdLocationRaw ?? null, { utcOffset }),
    parseLocationText((raw.htmlLocationText as string) ?? r.location_text ?? null, { utcOffset })
  );
  if (merged.countryCode) {
    resolved += 1;
    sqlPairs.push([r.id as string, merged.countryCode]);
    byCountry.set(merged.countryCode, (byCountry.get(merged.countryCode) ?? 0) + 1);
    console.log(
      `  ${merged.countryCode}  ${r.canonical_name?.slice(0, 62)}` +
        (merged.warnings.length ? `\n        ! ${merged.warnings.join(' | ')}` : '')
    );
  } else {
    stillNull.push(`${r.canonical_name?.slice(0, 50)} — "${r.location_text ?? 'no location text'}"`);
  }
}

if (process.argv.includes('--sql')) {
  console.log('\n-- generated by scripts/replay-country-resolution.ts --sql');
  console.log('-- candidate_id, resolved country');
  for (const [id, code] of sqlPairs) console.log(`  ('${id}'::uuid, '${code}'),`);
}

console.log(`\n${resolved} of ${rows.length} countryless candidates would now resolve`);
console.log([...byCountry.entries()].sort((a, b) => b[1] - a[1]).map(([c, n]) => `${c}=${n}`).join(' '));
console.log(`\nStill unresolved (${stillNull.length}) — these need a different fix or genuinely have no country on the page:`);
for (const s of stillNull) console.log(`  - ${s}`);
